public enum LocalizedText: String {
    case cannotConnectToICloud = "Cannot connect to iCloud"
    case capture = "Capture"
    case clear = "Clear"
    case expiration = "Expiration"
    case fullScreen = "Full Screen"
    case itemName = "Item name"
    case notes = "Notes"
    case noPhotosToShow = "No photos to show"
    case period = "Period"
    case photos = "Photos"
    case recapture = "Recapture"
    case remove = "Remove"
    case removeItem = "Remove item"
    case removePhoto = "Remove photo"
}
