public enum LocalizedText: String {
    case addItem = "Add item"
    case allLists = "All lists"
    case availableLists = "Available lists"
    case cannotConnectToICloud = "Cannot connect to iCloud"
    case capture = "Capture"
    case changeName = "Change name"
    case clear = "Clear"
    case expiration = "Expiration"
    case fullScreen = "Full Screen"
    case itemName = "Item name"
    case itemToMove = "Item to move"
    case listName = "List name"
    case moveItem = "Move item"
    case newList = "New list"
    case noListsAddedYet = "No lists added yet"
    case noListsAvailable = "No lists available for selected item"
    case noPhotosToShow = "No photos to show"
    case notes = "Notes"
    case period = "Period"
    case photos = "Photos"
    case recapture = "Recapture"
    case remove = "Remove"
    case removeItem = "Remove item"
    case removeList = "Remove list"
    case removePhoto = "Remove photo"
}
